src/routes/InstancesPage/InstancesPage.js
src/routes/InstancesPage/InstancesToolbarSearchFilter.js

The following adds toolbar filters to filter the data in the tables. We can filter by the following:
1. Name
2. Region `US-East, N. Virginia` and `EU-Ireland`
3. Owner 
4. Status - `Ready`, `Failed`, `Creation pending`, `Creation in progress`, and `Deleting`

feat: added filters (no backend)

---

README.md
config/dev.webpack.config.js
mocks/db.server.js
package.json

Made a few updates for simplicity:
1. We will use the same PORT (8000) for the Mock API endpoint so we don't have to have to have a conditional to proxy between 4000 and 8000
3. I fixed the `customProxy` value. I'm not sure why we were using the `process.env.BETA` to determine where to proxy. It might have been a mistake. It should have been the environment variable related to whether we're mocking or not
4. Because of `(2)`, I thought the extra command `npm run start:mock` wasn't necessary anymore so I removed that
5. Because of `(3)`, I updated the README

fix: Update Proxy Settings and README

---

mocks/db.server.js
src/hooks/apis/useCreateInstance.js
src/hooks/apis/useDeleteInstance.js
src/hooks/apis/useInstance.js
src/hooks/apis/useInstances.js

The backend APIs have changed since we first made the mock APIs. This PR will rename it to what was decided upon by the backend team
Backend API Spec: https://github.com/stackrox/acs-fleet-manager/blob/main/openapi/fleet-manager.yaml

feat: renaming mock APIs based on the actual backend APIs

---

config/dev.webpack.config.js
package.json

This PR adds the following new commands: 
```
npm run start:prod
npm run start:prod:beta
```
We can use these commands to run in prod (locally)

feat: adding command to use prod env

---

src/components/Status.js
src/hooks/apis/useDeleteInstance.js

Updates:
* Adding proper states for central instances requests: `accepted`, `preparing`, `provisioning`, `ready`, `failed`, `deprovision`, `deleting`
* Fixing the API for deleting an instance as backend suggested

fix: adding proper states for central instances and fixing the delete API

---

src/routes/InstancesPage/CreateInstanceModal.js

A super simple change for better error messages when trying to create a central request

fix: better error messages

---

src/hooks/useTableSort.js
src/routes/InstancesPage/InstancesPage.js

This change adds the ability to sort the table by column values. I am using the same `useTableSort` hook we employ in the `stackrox` project, but with a slight variation in the hook's output. Instead of using `reversed=true|false` we will be using `direction=asc|desc`
Note: I will try to add Typescript soon 😬

feat: adding table sorting

---

config/dev.webpack.config.js

This PR changes the proxy context from `/api` to `/api/rhacs` as a way to be safer about routing requests

fix: change proxy from /api->fleet manager endpoint to /api/rhacs->fleet manager endpoint

---

config/dev.webpack.config.js
src/services/apiRequest.js

This change removes the proxy to the Staging Fleet Manager API. Due to issues with sending a request directly to the endpoint, the backend had to make a change on the [app-interface](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44681). The fleet manager API is now available under [api.stage.openshift.com](http://api.stage.openshift.com/) so we can send a request to there instead

fix: remove proxy and use api.stage.openshift.com instead

---

src/routes/InstancesPage/CreateInstanceModal.js
src/routes/InstancesPage/InstancesPage.js
src/utils/cloudProvider.js
src/utils/date.js
src/utils/region.js

Modifying the values in the table to look a little nicer and more human readable

fix: better format for date, cloud provider, and region

---

src/routes/InstanceDetailsPage/InstanceDetailsPage.js

We want to use the Instance's `host` value for the `Sign in to ACS Instance` button so the user can access the UI endpoint. This replaces the placeholder we had before

fix: use correct url for 'Sign in to ACS Instance' button

---

src/routes/InstanceDetailsPage/InstanceDetailsPage.js

This PR changes the video used in the instance details view to use the correct `Advanced Cluster Security in 2 minutes` youtube video

feat: use the correct marketing video

---

package-lock.json
src/components/Status.js
src/routes/InstancesPage/InstanceDetailsDrawer.js
src/routes/InstancesPage/InstancesPage.js
src/routes/InstancesPage/InstancesToolbarSearchFilter.js
src/utils/cloudProvider.js
src/utils/date.js
src/utils/region.js
src/utils/searchQuery.js
src/utils/searchQuery.test.js
src/utils/status.js

This PR makes a few tweaks to the table filters to be able to be used with the API to filter the data. Some changes made in this PR include the following:
1. Three util files were created `status`, `cloudProvider` and `region` in order to expose a few things:
a. A `key-value` object where the `key` is the API-specific value and the `value` is the human-readable value (ie. `us-east-1` and `US-East, N. Virginia`)
b. An array of objects with a `value` and `label` that we can use for some of our select components
c. a `_ValueToLabel` and `_LabelToValue` function that lets us convert between something like `us-east-1` -> `US-East, N. Virginia` and `US-East, N. Virginia` -> `us-east-1`
2. A util file called `searchQuery` was added that exposes a function called `filtersToSearchQuery` that …

feat: integrate table filters with api

---

src/routes/InstancesPage/InstancesPage.js

As the title suggests, this PR will disable interactions on the table row when the instance is not ready:
1. Name link will be disabled
2. Clicking the row won't open the drawer
3. The table row actions won't show up

fix: disable interactions when instance is not ready

---

src/hooks/apis/useInstances.js
src/routes/InstancesPage/InstancesPage.js

This PR adds the ability to poll for the central instances every 10 seconds. Now you don't need to refresh the page to see the updated data
Try creating a central instance and deleting one to see the table update automagically. It takes a bit of time so sit back and relax

feat: added 10 second polling for the list of central instances

---

src/components/InstanceDetailsList.js
src/routes/InstanceDetailsPage/InstanceDetailsPage.js
src/routes/InstancesPage/InstanceDetailsDrawer.js

This PR changes the details page by doing the following:
1. Adding the instance details information
2. Adding a link to the Getting Started Guide
3. Adding a link to the Product Configuration 
Mocks: https://www.sketch.com/s/caf22e03-37ae-459f-a32d-f10e3f9c728b/a/My245Y3

refactor: improving the details page

---

config/plugins.js
src/services/apiRequest.js

We want to be able to utilize the api.openshift.com endpoint within a production environment vs. the api.stage.openshift.com endpoint within a staging environment. The following PR changes make that possible by adding an additional webpack plugin that exposes an environment variable called `PROD` that we can use within our `apiRequest` module

fix: distinguishing between the prod and stage openshift API

---

.github/workflows/build-prod.yml
.github/workflows/build-staging.yml
.github/workflows/deploy-main.yml
.github/workflows/deploy-prod-beta.yml
.github/workflows/deploy-prod-stable.yml
.github/workflows/deploy-stable.yml
package.json

The following changes in this PR should work with the changes I made in this PR https://github.com/RedHatInsights/acs-ui/pull/34 to so we can finally be able to utilize the api.openshift.com endpoint within a production environment vs. the api.stage.openshift.com endpoint within a staging environment. The changes I made were the following:
1. We separated the `build` command within package.json to `build:prod` and `build:staging` and we set the appropriate value for the `NODE_ENV` in each one
2. We will now have two separate build workflows (`Build Prod` and `Build Staging`) instead of just a `Build` workflow. Each of those will use the appropriate command mentioned in (1)
3. Each deploy-related workflow will now use the appropriate build workflow mentioned in (2)

feat: separating prod from staging

---

src/routes/InstancesPage/InstancesPage.js

This PR adds back the table row actions even when not in the ready state. Users may want to delete an instance if it's stuck in the creation phase
Reference: https://srox.slack.com/archives/C0313JYKH8W/p1663281667430639

feat: show table row actions even when not in ready state

---

src/routes/InstancesPage/InstancesPage.js

When there are no instances, we show the empty state. The problem was that when we poll the API, the empty state would disappear for a brief instance and show an empty table. This PR fixes the logic so we don't see that flickering anymore
Before:
https://user-images.githubusercontent.com/4805485/191098151-ebeceab2-3989-4c56-ad52-331d728f1928.mov
After:
No flickering

fix: flickering when polling

---

src/routes/InstancesPage/CreateInstanceModal.js

This PR clears the error message state, resets the form field state, and clears the state we use to tell if a request was made whenever the modal is closed
https://user-images.githubusercontent.com/4805485/191346479-5a55ffc3-43bb-4508-91a6-e064898b38dc.mov

feat: clear modal state before closing it

---

src/routes/OverviewPage/OverviewPage.js

Fix a typo in the Overview Page header

ROX-12847: fix overview page copy

---

src/routes/InstancesPage/DeleteInstanceModal.js

The delete modal currently refreshes the page and fails to delete the instance when a user hits enter on the input field. The expected behavior is the modal closes and the instance is deleted if the user hits enter.

ROX-12816: deleting instance with enter key

---

src/components/InstanceDetailsList.js

Update the label "Sensor Host URL" on the details page to "Central API Endpoint" to better align with the central cluster form

ROX-12782: change sensor host url label

---

config/dev.webpack.config.js
package.json

:warning: :warning: :warning: We migrated the stage fleet manager to use AMS as a quota backend. :warning: :warning: :warning:
As a result, requests must now come from [sso.redhat.com](http://sso.redhat.com/) accounts (e.g. the “normal” Red Hat account every employee has). At the same time, the UI has been moved to https://qaprodauth.cloud.redhat.com/application-services/acs/instances. Going forward, we must use the qaprodauth UI instead of the old [console.stage.redhat.com](http://console.stage.redhat.com/) UI. The latter still exists, but cannot create instances anymore. For the rationale behind the switch check out https://docs.google.com/document/d/12xq1ElAo6krniI-Yx_s8NB00Uzv1uQOKfH8IRxJpr08/edit?usp=sharing.
Because of the above changes, we need to run the UI in production mode when …

fix: using production mode in staging environment

---

src/App.js

Backend requested to prevent the use of the staging environment so this change will show an unavailable message in just that environment.
Reference to slack message: https://srox.slack.com/archives/C0313JYKH8W/p1665138184661119
- ~[ ] Unit and integration tests added~
No tests
```
npm run test
```

ROX-13007: deprecating staging environment

---

src/components/SelectSingle.js
src/hooks/apis/useCloudAccounts.js
src/routes/InstancesPage/CreateInstanceModal.js
src/routes/InstancesPage/InstancesPage.js

This PR adds an extra form field in the instance creation form for the **AWS account number**. The form field will use a **select** component that let's you choose among your different cloud accounts. 
Note: This PR is blocked until https://github.com/stackrox/acs-fleet-manager/pull/517 is merged
- ~[ ] Unit and integration tests added~
No Tests
```
npm run test
```

ROX-12152: added field for aws account number in central instance creation modal

---

src/routes/InstancesPage/CreateInstanceModal.js

This PR does the following:
* Place the AWS account selection directly below the Cloud Provider selection
* Auto-select the account if there is only one.
- ~[ ] CI and all relevant tests are passing~
- ~[ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~
```
npm run test
```

ROX-13382: reorder aws account number field in form and default select if only one available

---

src/routes/InstanceDetailsPage/InstanceDetailsPage.js
src/routes/InstancesPage/CreateInstanceModal.js
src/routes/InstancesPage/InstancesPage.js

This is a simple text change to use `cloud_account_id` instead of `aws_account_number`. Seems like there might have been a mistake or a miscommunication on the field text name.
I also fixed the youtube link
- ~[ ] Unit and integration tests added~
```
npm run test
```

ROX-13604 + ROX-13626: changing aws_account_number to cloud_account_id and fixing youtube link

---

src/components/InstanceDetailsList.js

Changing based on discussion in Slack thread, https://srox.slack.com/archives/C0313JYKH8W/p1670342527923849?thread_ts=1670341865.204039&cid=C0313JYKH8W
> rename entries in the cloud.r.c UI for clarity. Proposal:
> "Central API Endpoint" -> "Central API endpoint (Sensor mTLS)"
> "Central UI" -> "Central instance (UI, roxctl)"
Text change only.
Example:

Rename endpoints in instance detail view

---

src/routes/InstancesPage/InstancesPage.js

Before this change, we were accidentally using the length of the current API call as the total for the pagination components. This was never more than the selected per-page length, so it was impossible to navigation to other pages when there was more than one page worth of results available.
The total count for a query on the `/centrals` endpoint is already available as a property in the `data` object, so I simply used that.
```
{
"kind": "CentralRequestList",
"page": 2,
"size": 20,
"total": 22,
"items": [
{
"id": "ce7r92prdkj677csj2kg",
...
```
Correct top pagination:
Correct bottom pagination
Correct page 2

ROX-13745: Fix pagination total in Instances list

---

src/components/InstanceDetailsList.js
src/routes/InstanceDetailsPage/InstanceDetailsPage.js

To prevent the "Negative DNS caching" issue - situation when user accesses Central URL before being ready and failed response is cached in the DNS, now we're not exposing the URLs until Central become ready.
I made a few changes in the UI to show more clearly that we're unable to access the instance when it's provisioning. 
Local dev testing

ROX-13227: Make "Open ACS Console" button disabled until the instance becomes ready

---

src/routes/InstancesPage/DeleteInstanceModal.js

Simple UX enhancement
Tried to delete someone else's instance, and saw error message

ROX-13465: Surface error message when delete instance fails

---

src/routes/InstancesPage/CreateInstanceModal.js

Simplest fix for confusion found during HackFest testing.
> ...  user didn't think they could proceed when they saw the message "No accounts available".

ROX-13918: Hide cloud account selector if no accounts available

---

src/routes/InstancesPage/CreateInstanceModal.js

When only one account exists, we don't want to display the account selector field.
with one account:
with multiple accounts:

ROX-15005: Hide aws account in case only one exists

---

src/routes/OverviewPage/OverviewPage.js

Change text from `Managed Service` to `Cloud Service` and remove `Kubernetes` from the main header
Before: 
After:

ROX-14644: Change managed service text to cloud service

---

src/utils/cloudProvider.js
src/utils/cloudProvider.test.js

Clarify language in Cloud Provider column of ACS Instances table
Example:
Instead of "Amazon Web Services",  display "Hosted by Red Hat (on AWS)"
Screenshots

ROX-15884: Clarify cloud provider label in Instance

---

fec.config.js

https://github.com/RedHatInsights/acs-ui/pull/72 has apparently dropped a definition of the `PROD` env var that tells ACS console UI plugin to talk to the prod fleet manager instance instead of the default stage one.
This PR attempts to restore previous behavior in the new, appropriate location.
```
npm run test
```

Restore PROD env mapping via plugin

---

src/App.tsx
src/ProtectedRoute.tsx
src/Routes.tsx
src/context/AppContext.js
src/routes/OverviewPage/OverviewPage.js

Prevent the user from visiting gating routes using entitlement.
Check the entitlement flag using the `useChrome` `auth` property. Set up a way to flip entitlement on and off easily when developing locally.
When a user is not entitled, the `Get Started` button should not be visible on the Overview Page and all other pages aside from the Overview Page should redirect back to the Overview Page.
Entitlement can be turned on and off using the `enableEntitlementLocally` flag

Add protected routes using entitlement

---

.github/workflows/deploy-qa-beta.yml

Temporarily disable deploy-qa-beta GHA to see if it breaks the deployment. Can be considered as a workaround until the proper fix is implemented.
-

Temporarily disable deploy-qa-beta GHA to see if it breaks the deployment

---

src/routes/OverviewPage/OverviewPage.js

We’ll actually have two marketplace listings, one for non-EMEA customers and one for EMEA customers.
Also, we had to create new listings, so the link changed to AWS marketplace:
non-EMEA: https://aws.amazon.com/marketplace/pp/prodview-epwnwxab4jwdo
EMEA: https://aws.amazon.com/marketplace/pp/prodview-oefmjyqe64ces
1. Go the Overview page, on whichever env. it's being deployed to (/application-services/acs/overview)
2. Scroll down to the Purchase now widget box
3. Verify the heading now mentions EMEA as
4. Verify there are now two links for AWS Marketplace
Overview with NA link hovered
Overview with EMEA link hovered
NA AWS page targeted
EMEA AWS page targeted
```
npm run test
```

ROX-17213: Split AWS Marketplace link into NA and EMEA link options

---

src/components/NotFoundMessage.tsx
src/routes/InstanceDetailsPage/InstanceDetailsPage.js

When trying to access a non-existent instance (i.e. `/instances/instance/xxx`), the UI experiences a crash and displays a Sentry error. This can occur due to either the instance being deleted or an incorrect URL being entered. The former scenario can happen when clicking on an instance through `https://console.redhat.com/beta/application-services/subscriptions/rhacs`
We need to create a standard Not Found component to use in situations like this.

ROX-17475: Handle instance not found error

---

src/routes/OverviewPage/OverviewPage.js

No free tier at all for now.
We will add a link to the trial later.
Before this change:
After this change:

ROX-17945: Remove free tier line from Overview page

---

src/routes/OverviewPage/OverviewPage.js

Remove "Free Tier" language from qaprodauth "production" version

ROX-17945: Remove free tier line from Overview page (#99)

---

src/routes/InstancesPage/CreateInstanceModal.js

Everything else should remain the same -- when there are no AWS accounts, the dropdown should be disabled and the additional label text should show as above.

ROX-18074: Adding label text and disabling the dropdown when there is no AWS acct

---

src/routes/InstancesPage/CreateInstanceModal.js

As stated. The AWS dropdown is disabled when there is only one account and the helper text reads "The AWS account indicated, which is linked to your Red Hat organization, will be used for billing purposes." The behavior should still stay consistently disabled w associated helper text when there are no accounts available.

ROX-18075: Disabling AWS dropdown when there is only one account

---

src/routes/InstancesPage/CreateInstanceModal.js

As it states above. The `next` button should be disabled upon load even with the name filled out until the user has selected an AWS account number from the dropdown. The dropdown should still be disabled as expected when there are one or no AWS accounts found.

ROX-18076: Making AWS dropdown required when more than one acct

---

src/components/InstanceDetailsList.js

As the title states -- making ID, central API endpoint, and central instance details copyable via inline copy component in PatternFly. Should look like below:

ROX-16513: Making instance details copyable

---

src/utils/region.js
src/utils/searchQuery.test.js

Region filter was not working as expected for ACS Instances list (`undefined` was being passed through the API). It should filter properly now (should pass the region id now instead)

ROX-18739: Fixed region filter bug

---

src/routes/InstancesPage/CreateInstanceModal.js

As it states in the title above. It should look as below:

ROX-18865: removing Cloud Provider and Availability Zone form groups from create instance modal

---

src/hooks/apis/useApi.js

Added a case in the `useApi` hook to use the new `integration` endpoint when the UI is accessed on stage -> beta/preview as discussed.

Adding integration server case when stage/preview

---

package-lock.json
package.json

`rm -rf node_modules`
`npm i`
`npm run start` should run without issues
this is enabled due to stage/prod running on node 18 already https://redhat-internal.slack.com/archives/C023VGW21NU/p1695837441304849?thread_ts=1695834456.226359&cid=C023VGW21NU

ROX-19826: Bump Node to 18

---

README.md
fec.config.js
src/utils/paths.ts

As a preparation for moving ACS to Openshift bundle we have to adjust the app availability and basename. This PR addresses both of these things. With this PR ACS ui can operate on both application services and openshift bundle.
https://issues.redhat.com/browse/RHCLOUD-29707
- [-] Unit and integration tests added
- [-] Added test description under `Test manual`
- [-] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

Enable Openshift basename

---

src/routes/InstancesPage/InstancesPage.js
src/routes/InstancesPage/InstancesToolbarSearchFilter.js
src/utils/searchQuery.js
src/utils/searchQuery.test.js

Fixes the following issues with the ACS instance search:
- Applying a search no longer opens the "Create instance" modal in a way that locks the page
- The "Enter" key can be used to apply a text search, adding the value to the filters and clearing the input box
- Multiple text searches of a single category can be added at once (e.g. name/owner)
- The search query sent to the API is fixed to allow _substring_ matches instead of exact matches. 
Note that in the following tests, the rendering of some fields was overridden to redact the true values and replace text with `*` characters. Only the subset that matches an applied filter is not redacted in order to demonstrate that this works.
Visit "ACS Instances":
Apply a name filter by adding text and pressing "enter":
Add additional name …

ROX-27851: Fix functionality of ACS instance search UI

---

src/routes/GettingStartedPage/Wizard/InstallWithHelm.js

As titled, fixes `helm` installation documentation so that the commands work.
Also moves the section "If this is the first time you’re using helm, you will need to add the stackrox repo using the following commands" so that it is *before* the command that will error out if this step isn't completed.
Follow the instructions in the UI to set up an ACSCS instance, then secure an infra GKE cluster via this instance:
```
$ helm install -n stackrox --create-namespace \
stackrox-secured-cluster-services rhacs/secured-cluster-services \
-f /Users/dvail/Downloads/test-infra-cluster-Helm-values-cluster-init-bundle.yaml \
--set clusterName=dv-03-19-behind-change-nor \
--set centralEndpoint=acs-data-cvde5l1e4r9aim6ikat0.acs.rhcloud.com:443 \
--set imagePullSecrets.username='***********' \
--set …
```

ROX-26638: Fix helm install commands

---

deploy/frontend.yaml
package-lock.json
package.json

Frontend Operator migration as required by the crc-experiences team.
This moves configuration from the global https://github.com/RedHatInsights/chrome-service-backend repository into our app, allowing us to update navigation, service tiles, and search from within this repo.
See more context in the [migration guide](https://github.com/RedHatInsights/chrome-service-backend/blob/main/docs/feo-migration-guide.md), and a plan for how we make this live [on Slack](https://redhat-internal.slack.com/archives/C023VGW21NU/p1757694022226329).
None at the moment as this first step is not testable. For future testing steps, the following is the plan to complete the migration:
1. Merge our PR to the [RedHatInsights/acs-ui repo](https://github.com/RedHatInsights/acs-ui/pull/205/files) updating our …

Update frontend.yaml in support of the FEO migration
