.github/workflows/build.yml, package-lock.json, package.json
This is to get around an error when trying to run this frontend locally,
```
...node_modules/@redhat-cloud-services/frontend-components-config-utilities/repos/insights-chrome-build/snippets/head.html'
```
See this Slack convo for context:
https://coreos.slack.com/archives/C023VGW21NU/p1654091594517949
=> Update dependencies for Akamai

src/App.scss, src/routes/InstanceDetailsPage/InstanceDetailsPage.js
Static version of the Sketch mock (https://www.sketch.com/s/caf22e03-37ae-459f-a32d-f10e3f9c728b/a/My245Y3)
=> Make static version of instance detail

README.md
Updating the README with clearer instructions for running the Backend Fleet Manager API
=> refactor: changing the README

config/dev.webpack.config.js
I was recommended to add the `changeOrigin` option to the proxy to help with the issues in the staging environment. There are still other issues, but this is needed as well
=> feat: adding change origin to proxy

src/routes/InstancesPage/InstanceDetailsDrawer.js, src/routes/InstancesPage/InstancesPage.js, src/utils/date.js
Just making some tweaks to make the UI look a little neater
=> refactor: making the drawer data look a little neater

src/routes/InstanceDetailsPage/InstanceDetailsPage.js
This PR fixes "Open ACS Console" button, since it doesn't reflect changes in URL format.
=> Fix central link

.github/workflows/build-staging-beta.yml, .github/workflows/deploy-main.yml, .github/workflows/deploy-prod-beta.yml, .github/workflows/deploy-prod-stable.yml, .github/workflows/deploy-stable.yml, package.json
Added a new script command called `build:staging:beta` which is similar to `build:staging` except it sets the environment variable for `BETA=true`. Hoping these changes help with getting things to work on qaprodauth
=> fix: changing workflow files to get things working on qaprodauth

src/utils/region.js, src/utils/searchQuery.test.js
Title says it all.
Ask from back-end team on Slack,
https://srox.slack.com/archives/C0313JYKH8W/p1663763036080469
=> ROX-12749: Remove eu-west-1 as option for region of instance

.github/workflows/build-prod-beta.yml, .github/workflows/deploy-prod-beta.yml, package.json
Differentiating prod beta from prod stable
=> feat: fixing prod beta environment

README.md
This PR updates the README with clearer up-to-date instructions
=> refactor: updating the README

.github/pull_request_template.md, CONTRIBUTING.md, README.md
The PR will add the following:
1. A PR template for a more structured way of creating PRs
2. A CONTRIBUTING.md file that onboards new engineers and gives them information about how things work
- ~~[ ] Unit and integration tests added~~
- ~~[ ] Added test description under `Test manual`~~
- ~~[ ] CI and all relevant tests are passing~~
- ~~[ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~
No tests
=> ROX-12980: added PR template and onboarding instructions

src/components/SelectSingle.js
Fixing the issue where the page reloads when we click on the select element in the dropdown
https://issues.redhat.com/browse/ROX-13669
- ~[ ] Unit and integration tests added~
```
npm run test
```
=> ROX-13669: Fix page reload on clicking select element

src/components/InstanceDetailsList.js, src/routes/InstanceDetailsPage/InstanceDetailsPage.js, src/routes/InstancesPage/CreateInstanceModal.js, src/routes/InstancesPage/DeleteInstanceModal.js, src/routes/InstancesPage/InstancesPage.js
Deploying 3 tasks to `qa-stable`
1. [ROX-13745: Fix pagination total in Instances list](https://github.com/RedHatInsights/acs-ui/pull/58)
2. [Rename endpoints in instance detail view](https://github.com/RedHatInsights/acs-ui/pull/57)
3. https://github.com/RedHatInsights/acs-ui/pull/63
4. https://github.com/RedHatInsights/acs-ui/pull/62
Tested in merge to main
=> Deploy Fix pagination total and Rename endpoints in instance detail to qa-stable

src/components/InstanceDetailsList.js, src/routes/InstanceDetailsPage/InstanceDetailsPage.js, src/routes/InstancesPage/CreateInstanceModal.js, src/routes/InstancesPage/DeleteInstanceModal.js, src/routes/InstancesPage/InstancesPage.js
Deploying 2 tasks to `prod-beta`
1. [ROX-13745: Fix pagination total in Instances list](https://github.com/RedHatInsights/acs-ui/pull/58)
2. [Rename endpoints in instance detail view](https://github.com/RedHatInsights/acs-ui/pull/57)
3. https://github.com/RedHatInsights/acs-ui/pull/63
4. https://github.com/RedHatInsights/acs-ui/pull/62
Tested in merge to main
=> Deploy Fix pagination total and Rename endpoints in instance detail to prod-beta

src/App.js, src/hooks/useAnalytics.js, src/routes/InstancesPage/CreateInstanceModal.js, src/routes/InstancesPage/DeleteInstanceModal.js, src/routes/InstancesPage/InstancesPage.js
Add segment analytics when creating and deleting an instance
=> Add segment analytics for instance creation and deletion 

src/utils/region.js, src/utils/searchQuery.test.js
Add capability to select Europe (Frankfurt) region to provision ACS instance
=> ROX-14352: Add EU Frankfurt region

src/utils/region.js, src/utils/searchQuery.test.js
The request comes due to a cost benefit and the additional advantage of EU West receiving features faster than EU Central
=> ROX-16107: Change EU Central region to EU West

src/routes/InstancesPage/DeleteInstanceModal.js
=> fix spelling

.travis/custom_release.sh
Adds custom release
main -> console.stage.redhat.com/beta
prod-beta -> console.redhat.com/beta
stage-stable -> console.stage.redhat.com
prod-stable -> console.redhat.com
```
npm run test
```
=> add custom release

.travis.yml
Adds the deploy step to Travis CI
=> Add deploy step to travis

README.md, package-lock.json, package.json
Update `@redhat-cloud-services/frontend-components-config` and `README` to better prepare for the switch from beta to preview
Can run locally here `https://prod.foo.redhat.com:1337/preview/application-services/acs`
=> ROX-16399: Switch from beta to preview

src/components/InstanceDetailsList.js, src/components/RegionLabel.js, src/hooks/apis/useCloudRegions.js, src/routes/InstancesPage/CreateInstanceModal.js, src/routes/InstancesPage/InstancesPage.js, src/routes/InstancesPage/InstancesToolbarSearchFilter.js, src/utils/cloudProvider.js, src/utils/cloudProvider.test.js, src/utils/region.js, src/utils/searchQuery.js, src/utils/searchQuery.test.js
Use the cloud regions obtained from the API
- Verify that the central instances show the appropriate cloud region
- Verify that the `Create ACS Instance` modal displays the available cloud regions
- Verify that user can search by cloud region display name
- Verify that the user can filter by the available cloud regions
```
npm run test
```
=> ROX-16500 Use cloud regions from API

src/routes/GettingStartedPage/Wizard/InitialSetup.js
Open instances page in a new tab on initial setup page
Manually testing
=> Open instances page in a new tab on initial setup page

src/routes/GettingStartedPage/Wizard/InitialSetup.js, src/routes/GettingStartedPage/Wizard/InstallOptions.js, src/routes/OverviewPage/OverviewPage.js
Overview Page
before: `Red Hat Advanced Cluster Security for Kubernetes RHACS Cloud Service lowers operational costs...`
after: `RHACS Cloud Service lowers operational costs...`
Also includes text changes to the Getting Started page
=> Small text changes

src/routes/OverviewPage/OverviewPage.js
=> Testing qa revert

src/routes/OverviewPage/OverviewPage.js
Reverts RedHatInsights/acs-ui#90
=> Revert "Testing qa revert"

.github/workflows/deploy-qa-beta.yml, src/ProtectedRoute.tsx, src/Routes.tsx, src/routes/InstancesPage/InstancesPage.js, src/routes/OverviewPage/OverviewPage.js
Merge up qa-beta for smoke-testing on qaprodauth env.
Check that changes for https://issues.redhat.com/browse/ROX-17213 after this is merged and deployed to qaprodauth
=> ROX-17213: Merge up qa-beta for smoke-testing on qaprodauth env

.github/workflows/deploy-qa-beta.yml, src/ProtectedRoute.tsx, src/Routes.tsx, src/routes/InstancesPage/InstancesPage.js, src/routes/OverviewPage/OverviewPage.js
Merge up qa-beta for smoke-testing on qaprodauth env.
Check that changes for https://issues.redhat.com/browse/ROX-17213 after this is merged and deployed to qaprodauth
=> ROX-17213: Merge up prod-beta

src/routes/OverviewPage/OverviewPage.js
Remove "Free Tier" language from qaprodauth/preview
=> ROX-17945: Remove free tier line from Overview page (#99)

README.md
Add qa branch information to readme and update urls to point directly to acs
=> Update readme to include qa branches

src/components/InstanceDetailsList.js, src/routes/InstancesPage/CreateInstanceModal.js
=> Merge main into qa-beta

src/components/InstanceDetailsList.js, src/routes/InstancesPage/CreateInstanceModal.js
=> Merge main into qa-stable

src/components/InstanceDetailsList.js, src/routes/InstancesPage/CreateInstanceModal.js
=> Merge main into prod-beta

src/components/InstanceDetailsList.js, src/routes/InstancesPage/CreateInstanceModal.js
=> Merge main into prod-stable

src/routes/InstancesPage/CreateInstanceModal.js
=> ROX-19572: Move select options to append outside of Create instance modal

src/AppEntry.tsx
I'm not sure how the linter missed this/rendered fine, but @pedrottimark noted that this is weird in the PR after it was merged https://github.com/RedHatInsights/acs-ui/pull/132#discussion_r1333469288
=> Fix for React 18 upgrade lint issue

src/routes/OverviewPage/OverviewPage.js
=> ROX-19505: Adding 'Start free trial' button when user is not entitled

src/routes/InstanceDetailsPage/InstanceDetailsPage.js
=> Removed extra header text from card header

src/routes/InstancesPage/InstancesPage.js
As it states -- fixes the handling of actions dropdown vs row click.
=> Table row click/actions dropdown handler fix

src/routes/InstanceDetailsPage/InstanceDetailsPage.js, src/routes/InstancesPage/InstancesPage.js
=> Merge up qa-stable with main

custom.d.ts, src/routes/OverviewPage/GetStartedCard.tsx, src/routes/OverviewPage/OverviewPage.js
Creating card for the `Getting started` card as shown above.
=> ROX-20587: Adding "Getting started" card component

src/routes/OverviewPage/PricingSection.tsx
Still need to update the links to proper locations. Also tried doing things more semantically -- not sure if there's a more "PatternFly" way to go about it, but it came out pretty close to the mock so I left it 🤷🏼‍♀️
=> ROX-20589: Adding Pricing help section

src/routes/OverviewPage/OverviewPage.js, src/routes/OverviewPage/ProductDocumentationCard.tsx
=> ROX-20590: Adding product documentation card

src/routes/OverviewPage/DescriptionsCard.tsx, src/routes/OverviewPage/ExpandableDescription.tsx
As title states -- this is only the component.  The copy is directly from the mocks. Once the PR goes in & we merge up qa, I will share w Doron & Ajmal to confirm the copy is good.
I'm unsure how to make expandable section titles not links though...
```
npm run test
```
=> ROX-20588: Adding expandable description sections

src/routes/OverviewPage/OverviewPage.js, src/routes/OverviewPage/ProductDemoCard.tsx
Added product demo card and re-laid out the Overview Page w new cards
mocks for comparison: https://www.sketch.com/s/caf22e03-37ae-459f-a32d-f10e3f9c728b/a/zyb557y
=> ROX-21272: Laying out new Overview page

src/routes/OverviewPage/DescriptionsCard.tsx, src/routes/OverviewPage/PricingSection.tsx
Updating copy based on feedback.
=> Overview Page copy fixes

deploy/frontend.yaml
Adds the frontend.yaml resource file for containerization of the ACS UI according to https://consoledot.pages.redhat.com/docs/dev/containerized-frontends/migration/migration.html#_step_5_create_the_frontend_resource_yaml
TBD - Unaware of any way to test other than deploying to an ephemeral cluster
=> Add frontend resource YAML for containerized build

README.md
Updates README to reflect new changes in build and deploy process.
Note: This is easier to review by viewing the repo against branch `dv/update-readme-for-containerized-deploys` and seeing the rendered markdown.
=> Update README to reflect new build and deploy processes

README.md, package-lock.json, package.json
Updates the required package as per https://issues.redhat.com/browse/RHCLOUD-34669 and https://issues.redhat.com/browse/ROX-25814
Run the app with `npm run start` on VPN, selecting "prod".
<Screenshot of production instances omitted>
=> Update the frontend-components-config package

README.md
The goal for the PR:
- Add docs for Konflux setup
- Trigger Konflux Release process to see if it's fixed (related: https://gitlab.cee.redhat.com/releng/konflux-release-data/-/commit/435312df5037920fdd9b7ac24927edda7f5851c9)
N/A
=> ROX-26522: Add Konflux docs

package.json, src/routes/GettingStartedPage/Wizard/GettingStartedWizard.tsx, src/routes/GettingStartedPage/Wizard/InstallOptions.tsx, src/routes/GettingStartedPage/Wizard/InstallWithHelm.js
Updates the deprecated version of the Wizard component to the current version in preparation for PF 6.
https://github.com/user-attachments/assets/90f3744d-bd8b-42b7-a11f-7979492ada7b
=> Upgrade PF Wizard to non-deprecated version

.tekton/acscs-ui-pull-request.yaml, .tekton/acscs-ui-push.yaml
Should fix tekton contract CI
```
N/A
```
=> Add rpms signature scan tekton task

.gitmodules, .tekton/acscs-ui-pull-request.yaml, .tekton/acscs-ui-push.yaml
As required per https://groups.google.com/a/redhat.com/g/hcc-actions-required/c/GBnHsrzoF8E/m/glTlFp9yAQAJ
Close https://issues.redhat.com/browse/ROX-28199 as well once this is merged
Verify that CI build is successful: https://ci.ext.devshift.net/job/RedHatInsights-acs-ui-pr-check/54/
Builds that actually use this image will not happen until all applications have migrated and the console team puts this into production.
=> ROX-28218: Migrate to shared submodule Containerfile

.tekton/acscs-ui-pull-request.yaml, .tekton/acscs-ui-push.yaml
Add sast-shell-check, sast-unicode-check and sast-coverity-check. Those tasks will be required by 2025-04-01 according to Konflux logs
N/A
=> Konflux: Add sast-shell sast-unicode and sast-coverity checks

deploy/frontend.yaml
How do we know if the migration to the frontend operator is working, or if we have not yet switched over?
By making a small change of the link from "Getting Started" to "Getting started". We can use the lowercase letter change as an indication that all is good in production and swap it back after the migration.
```
npm run test
```
=> Temporarily change caps as a smoke test that we are using the correct config
